# Generated by Django 5.2.2 on 2025-12-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('planner', 'Planner'), ('supervisor', 'Supervisor'), ('worker', 'Worker'), ('quality', 'Quality Officer'), ('maintenance', 'Maintenance')], max_length=50, unique=True),
        ),
    ]
