# Generated by Django 5.2.11 on 2026-02-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='app_scope',
            field=models.CharField(choices=[('planner', 'Planner'), ('quality', 'Quality'), ('maintenance', 'Maintenance')], default='planner', max_length=20),
        ),
    ]
