# Generated by Codex on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_app_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
