# Generated by Codex on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="shift",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
