# Generated by Django 5.2.11 on 2026-02-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Globally unique company owner email used at registration/login onboarding.', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='db_name',
            field=models.CharField(help_text='Tenant database entry: PostgreSQL URL or legacy SQLite path.', max_length=255),
        ),
    ]
