# Generated by Django 5.2.11 on 2026-04-08 22:15

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def backfill_organizations(apps, schema_editor):
    Organization = apps.get_model("tenancy", "Organization")
    Tenant = apps.get_model("tenancy", "Tenant")

    used_slugs = set(Organization.objects.using(schema_editor.connection.alias).values_list("slug", flat=True))

    for tenant in Tenant.objects.using(schema_editor.connection.alias).all().order_by("id"):
        if tenant.organization_id:
            continue

        base_slug = slugify(tenant.code or tenant.name) or f"org-{tenant.pk}"
        slug = base_slug
        suffix = 2
        while slug in used_slugs:
            slug = f"{base_slug}-{suffix}"
            suffix += 1

        organization = Organization.objects.using(schema_editor.connection.alias).create(
            name=tenant.name,
            slug=slug,
            owner_email=tenant.owner_email,
            status="active" if tenant.is_active else "suspended",
            seat_limit=1,
            wants_test_environment=False,
        )
        used_slugs.add(slug)

        tenant.organization_id = organization.id
        tenant.environment_type = "live"
        tenant.is_primary = True
        tenant.save(update_fields=["organization", "environment_type", "is_primary"])


def rollback_organizations(apps, schema_editor):
    Tenant = apps.get_model("tenancy", "Tenant")
    Organization = apps.get_model("tenancy", "Organization")

    Tenant.objects.using(schema_editor.connection.alias).update(organization=None)
    Organization.objects.using(schema_editor.connection.alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_tenant_owner_email_alter_tenant_db_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Stable organization key, e.g. al-nour', max_length=64, unique=True)),
                ('owner_email', models.EmailField(blank=True, help_text='Globally unique organization owner email used at registration/login onboarding.', max_length=254, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('seat_limit', models.PositiveIntegerField(default=1)),
                ('wants_test_environment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='environment_type',
            field=models.CharField(choices=[('live', 'Live'), ('test', 'Test'), ('dev', 'Dev')], default='live', max_length=16),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hostname',
            field=models.CharField(blank=True, help_text='Optional hostname used for host-based tenant resolution, e.g. al-nour.nezam.com', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Legacy owner email retained for backward compatibility.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tenancy.organization'),
        ),
        migrations.RunPython(backfill_organizations, rollback_organizations),
    ]
