# Generated by Django 5.2.11 on 2026-04-08 22:52

from decimal import Decimal
from django.db import migrations, models


def create_default_platform_settings(apps, schema_editor):
    PlatformSettings = apps.get_model("tenancy", "PlatformSettings")
    PlatformSettings.objects.using(schema_editor.connection.alias).get_or_create(singleton_key="default")


def delete_default_platform_settings(apps, schema_editor):
    PlatformSettings = apps.get_model("tenancy", "PlatformSettings")
    PlatformSettings.objects.using(schema_editor.connection.alias).filter(singleton_key="default").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_organization_tenant_environment_type_tenant_hostname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=32, unique=True)),
                ('subscription_currency', models.CharField(default='USD', max_length=8)),
                ('base_monthly_price', models.DecimalField(decimal_places=2, default=Decimal('149.00'), max_digits=10)),
                ('included_users', models.PositiveIntegerField(default=5)),
                ('extra_user_monthly_price', models.DecimalField(decimal_places=2, default=Decimal('11.00'), max_digits=10)),
                ('test_environment_monthly_price', models.DecimalField(decimal_places=2, default=Decimal('49.00'), max_digits=10)),
                ('guided_onboarding_one_time_fee', models.DecimalField(decimal_places=2, default=Decimal('240.00'), max_digits=10)),
                ('annual_discount_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1200'), help_text='Fractional discount rate. Example: 0.1200 = 12% annual discount.', max_digits=5)),
                ('manual_quote_email', models.EmailField(default='sales@kemet-erp.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.RunPython(create_default_platform_settings, delete_default_platform_settings),
    ]
