# Generated by Django 5.2.8 on 2025-11-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_billofmaterial_productionstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='color',
            field=models.CharField(default='#90CAF9', help_text='Stage color in HEX, e.g. #ff9800', max_length=20),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='machines',
            field=models.ManyToManyField(blank=True, related_name='stages', to='manufacturing.machine'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='order',
            field=models.PositiveIntegerField(help_text='Stage order sequence'),
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manufacturing.billofmaterial')),
            ],
        ),
    ]
