# Generated by Django 5.2.8 on 2025-11-07 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_productionstage_color_productionstage_machines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='product_code',
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='components',
            field=models.TextField(default=django.utils.timezone.now, help_text='List of raw materials or parts required'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
