# Generated by Django 5.2.8 on 2025-11-08 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_remove_billofmaterial_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstage',
            name='machines',
        ),
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='manufacturing.machine'),
            preserve_default=False,
        ),
    ]
