# Generated by Django 5.2.8 on 2025-11-08 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_remove_productionstage_machines_machine_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='pcs', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='components',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='billofmaterial',
            name='quantity',
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='version',
            field=models.CharField(default='v1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Stage order sequence'),
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='manufacturing.billofmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='manufacturing.product'),
        ),
        migrations.DeleteModel(
            name='BOMItem',
        ),
    ]
