# Generated by Django 5.2.8 on 2025-11-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0007_product_remove_billofmaterial_components_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.machine'),
        ),
    ]
