# Generated by Django 5.2.8 on 2025-11-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_alter_workorder_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='parent_bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_boms', to='manufacturing.billofmaterial'),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='is_subassembly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='source',
            field=models.CharField(choices=[('purchase', 'Purchased'), ('production', 'Produced Internally'), ('stock', 'From Inventory')], default='stock', max_length=20),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='wastage_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='material_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='color',
            field=models.CharField(default='#90CAF9', help_text='HEX color', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.machine'),
        ),
    ]
