# Generated by Django 5.2.8 on 2025-11-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_billofmaterial_parent_bom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomcomponent',
            name='is_subassembly',
        ),
        migrations.RemoveField(
            model_name='bomcomponent',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='bomcomponent',
            name='source',
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='source_type',
            field=models.CharField(choices=[('raw', 'Raw Material'), ('semi_finished', 'Semi-Finished'), ('finished', 'Finished Product')], default='raw', max_length=50),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='sub_bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in', to='manufacturing.billofmaterial'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='material_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='wastage_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wastage %', max_digits=5),
        ),
    ]
