# Generated by Django 5.2.8 on 2025-11-09 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0010_remove_bomcomponent_is_subassembly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomcomponent',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='bomcomponent',
            name='wastage_percent',
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='sub_bom',
            field=models.ForeignKey(blank=True, help_text='If this component is a sub-assembly, link its BOM here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_components', to='manufacturing.billofmaterial'),
        ),
    ]
