# Generated by Django 5.2.8 on 2025-11-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0011_remove_bomcomponent_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponent',
            name='source_type',
            field=models.CharField(choices=[('raw', 'Raw Material'), ('semi_finished', 'Semi-Finished'), ('finished', 'Finished Product')], default='raw', max_length=50),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='wastage_percent',
            field=models.FloatField(default=0),
        ),
    ]
