# Generated by Django 5.2.8 on 2025-11-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0012_bomcomponent_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
