# Generated by Django 5.2.2 on 2025-12-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0013_workorder_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='maintenance_note',
            field=models.TextField(blank=True, help_text='Current maintenance status or issue.', null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('broken', 'Broken'), ('inactive', 'Inactive')], default='operational', max_length=20),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='is_quality_check',
            field=models.BooleanField(default=False, help_text='Is this a QA stage?'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_work_orders', to='manufacturing.productionstage'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='manufacturing.machine'),
        ),
        migrations.CreateModel(
            name='MachineFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='manufacturing.machine')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('good_quantity', models.PositiveIntegerField(default=0)),
                ('repair_quantity', models.PositiveIntegerField(default=0)),
                ('faulty_quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='manufacturing.workorder')),
            ],
        ),
    ]
