# Generated by Django 5.2.2 on 2025-12-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0015_productionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponent',
            name='scrap_value_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Value of waste per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='wastage_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantity that becomes waste', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Gross Quantity Required', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='unit',
            field=models.CharField(choices=[('kg', 'KG'), ('gm', 'Gram'), ('m', 'Meter'), ('cm', 'CM'), ('l', 'Liter'), ('pcs', 'Pcs')], default='pcs', max_length=10),
        ),
    ]
