# Generated by Django 5.2.2 on 2025-12-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0016_bomcomponent_scrap_value_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='base_quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Batch Size for this BOM', max_digits=10),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Editable)'), ('active', 'Active (Production Ready)'), ('archived', 'Archived (History)')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='scrap_type',
            field=models.CharField(choices=[('irretrievable', 'Irretrievable Loss (Cost Absorbed)'), ('sell_as_scrap', 'Sell as Scrap (Recover Value)'), ('return_to_stock', 'Return to Stock (Re-use)')], default='sell_as_scrap', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='material_type',
            field=models.CharField(choices=[('raw', 'Raw Material'), ('semi', 'Semi-Finished'), ('finished', 'Finished Product'), ('packaging', 'Packaging')], default='raw', max_length=20),
        ),
    ]
