# Generated by Django 5.2.2 on 2025-12-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0017_billofmaterial_base_quantity_billofmaterial_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='uom',
            field=models.CharField(choices=[('kg', 'KG'), ('gm', 'Gram'), ('m', 'Meter'), ('cm', 'CM'), ('l', 'Liter'), ('pcs', 'Pcs')], default='pcs', help_text='Unit of Measure for Base Qty', max_length=10),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Gross Quantity Required per Base Qty', max_digits=10),
        ),
    ]
