# Generated by Django 5.2.2 on 2025-12-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0018_billofmaterial_uom_alter_bomcomponent_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Editable)'), ('test', 'Test (Simulation Only)'), ('active', 'Active (Production Ready)'), ('archived', 'Archived (History)')], default='draft', max_length=20),
        ),
    ]
