# Generated by Django 5.2.9 on 2025-12-31 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0021_alter_workorder_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='manufacturing.workorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Initial/planned stage', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.productionstage'),
        ),
    ]
