# Generated by Django 5.2.9 on 2025-12-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0022_workorder_parent_alter_workorder_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=20),
        ),
    ]
