# Generated by Django 5.2.9 on 2026-01-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0023_workorder_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='total_runtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours run since last maintenance', max_digits=10),
        ),
    ]
