# Generated by Django 5.2.9 on 2026-01-01 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0024_machine_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subscription_plan', models.CharField(choices=[('free_trial', 'Free Trial (30 Days)'), ('pro', 'Pro Plan'), ('enterprise', 'Enterprise')], default='free_trial', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
