# Generated by Django 5.2.9 on 2026-01-06 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0026_machine_company_product_company_workorder_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='scheduled_start_date',
            field=models.DateTimeField(blank=True, help_text='Planned start time', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Actual start time', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending (Scheduled)'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('hold', 'On Hold'), ('canceled', 'Canceled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login'), ('permission_denied', 'Permission Denied'), ('suspicious_activity', 'Suspicious Activity'), ('data_breach_attempt', 'Data Breach Attempt'), ('unauthorized_access', 'Unauthorized Access')], max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export Data'), ('import', 'Import Data'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='manufacturi_user_id_db4812_idx'), models.Index(fields=['company', 'timestamp'], name='manufacturi_company_843f41_idx'), models.Index(fields=['model_name', 'timestamp'], name='manufacturi_model_n_ce5ad3_idx')],
            },
        ),
    ]
