# Generated by Django 5.2.9 on 2026-01-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0027_workorder_scheduled_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMAcceptanceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(help_text='e.g. Dimensions, Surface Finish', max_length=200)),
                ('method', models.CharField(help_text='e.g. Visual, Caliper, Gauge', max_length=100)),
                ('criteria_min', models.CharField(blank=True, help_text='Minimum acceptable value', max_length=50, null=True)),
                ('criteria_max', models.CharField(blank=True, help_text='Maximum acceptable value', max_length=50, null=True)),
                ('pass_fail', models.BooleanField(default=False, help_text='If true, this is a simple Pass/Fail check')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_criteria', to='manufacturing.billofmaterial')),
            ],
        ),
    ]
