# Generated by Django 5.2.9 on 2026-01-06 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0028_bomacceptancecriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=10)),
                ('production_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usage', to='manufacturing.productionlog')),
            ],
        ),
    ]
