# Generated by Django 5.2.9 on 2026-01-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0030_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomoperation',
            name='run_time',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Run time in minutes per single unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='bomoperation',
            name='setup_time',
            field=models.PositiveIntegerField(default=0, help_text='Setup time in minutes (once per batch)'),
        ),
        migrations.AlterField(
            model_name='bomoperation',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Total estimated duration (deprecated)'),
        ),
    ]
