# Generated by Django 5.2.9 on 2026-01-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0031_bomoperation_run_time_bomoperation_setup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomacceptancecriteria',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='If true, failure rejects the whole batch'),
        ),
        migrations.AddField(
            model_name='bomacceptancecriteria',
            name='target_value',
            field=models.CharField(blank=True, help_text='Target value (e.g. 10mm)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bomacceptancecriteria',
            name='tolerance',
            field=models.CharField(blank=True, help_text='Tolerance (e.g. +/- 0.05mm)', max_length=100, null=True),
        ),
    ]
