# Generated by Django 5.2.9 on 2026-01-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0032_bomacceptancecriteria_is_critical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomoperation',
            name='description',
            field=models.TextField(blank=True, help_text='Instructions, QC Triggers, or comments for this step.', null=True),
        ),
    ]
