# Generated by Django 5.2.9 on 2026-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0033_bomoperation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per hour to run this machine', max_digits=10),
        ),
    ]
