# Generated by Django 5.2.9 on 2026-01-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0034_machine_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_split',
            field=models.BooleanField(default=False, help_text='True if this is a parent WO for a split job'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.company')),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.customer'),
        ),
    ]
