# Generated by Django 5.2.9 on 2026-01-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0035_workorder_is_split_customer_workorder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Customer deadline for order completion', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Actual start time (set during scheduling)', null=True),
        ),
        migrations.CreateModel(
            name='WorkOrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(default=0, help_text='Order in the production flow')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(help_text='Quantity to produce in this stage (for split production)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('depends_on', models.ManyToManyField(blank=True, help_text='Stages that must complete before this one', to='manufacturing.workorderstage')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.machine')),
                ('stage', models.ForeignKey(help_text='BOM operation/stage', on_delete=django.db.models.deletion.PROTECT, to='manufacturing.productionstage')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='manufacturing.workorder')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
    ]
