# Generated by Django 5.2.9 on 2026-01-14 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0037_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', max_length=10)),
                ('holidays', models.JSONField(blank=True, default=list, help_text="List of holiday dates [{'date': 'YYYY-MM-DD', 'name': 'New Year'}]")),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='manufacturing.company')),
            ],
        ),
    ]
