# Generated by Django 5.2.9 on 2026-01-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0038_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='weekly_holidays',
            field=models.JSONField(blank=True, default=list, help_text='List of day indices (0-6) that are recurring holidays (e.g. [4, 5] for Friday, Saturday)'),
        ),
    ]
