# Generated by Django 5.2.9 on 2026-01-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0039_systemsettings_weekly_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='instructions',
            field=models.TextField(blank=True, help_text='Special instructions from the planner', null=True),
        ),
    ]
