# Generated by Django 5.2.9 on 2026-01-16 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0040_workorder_instructions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, help_text='Worker assigned to this WO (auto from shift or manual override)', limit_choices_to={'profile__role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assignment_type',
            field=models.CharField(choices=[('auto', 'Automatic (from shift)'), ('manual', 'Manual Override')], default='auto', help_text='How worker was assigned', max_length=20),
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('day', 'Day Shift (6AM-2PM)'), ('middle', 'Middle Shift (2PM-10PM)'), ('night', 'Night Shift (10PM-6AM)')], max_length=20)),
                ('date', models.DateField(help_text='Which day this assignment applies to')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'profile__role__in': ['supervisor', 'planner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='manufacturing.machine')),
                ('worker', models.ForeignKey(limit_choices_to={'profile__role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Assignment',
                'verbose_name_plural': 'Shift Assignments',
                'ordering': ['date', 'shift_type', 'machine'],
                'unique_together': {('worker', 'shift_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='basic', max_length=20)),
                ('certified_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Certification notes, training records', null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certified_workers', to='manufacturing.machine')),
                ('worker', models.ForeignKey(limit_choices_to={'profile__role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker Certification',
                'verbose_name_plural': 'Worker Certifications',
                'unique_together': {('worker', 'machine')},
            },
        ),
    ]
