# Generated by Django 5.2.9 on 2026-01-20 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0041_workorder_assigned_worker_workorder_assignment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='shift_configuration',
            field=models.JSONField(blank=True, default=dict, help_text="Custom shift timings e.g. {'morning': {'start': '06:00', 'end': '14:00'}}"),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'profile__role__name__in': ['supervisor', 'planner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='worker',
            field=models.ForeignKey(limit_choices_to={'profile__role__name': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workercertification',
            name='worker',
            field=models.ForeignKey(limit_choices_to={'profile__role__name': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, help_text='Worker assigned to this WO (auto from shift or manual override)', limit_choices_to={'profile__role__name': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
