# Generated by Django 5.2.9 on 2026-01-20 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0042_systemsettings_shift_configuration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='generated_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quality_check', to='manufacturing.workorder'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processed', 'Processed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='order_type',
            field=models.CharField(choices=[('production', 'Production'), ('repair', 'Repair')], default='production', help_text='Type of order: Production or Repair', max_length=20),
        ),
    ]
