# Generated by Django 5.2.9 on 2026-01-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0043_qualitycheck_generated_wo_qualitycheck_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_assign_workers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_fault_lockdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='predictive_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='trouble_ticket_integration',
            field=models.BooleanField(default=True),
        ),
    ]
