# Generated by Django 5.2.9 on 2026-01-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0044_systemsettings_auto_assign_workers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomoperation',
            name='machine_type',
            field=models.CharField(blank=True, help_text="Generic machine requirement (e.g. 'CNC')", max_length=100, null=True),
        ),
    ]
