# Generated by Django 5.2.9 on 2026-01-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0045_bomoperation_machine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='category',
            field=models.CharField(blank=True, help_text="Broad Category matching BOM (e.g. 'CNC', 'Assembly')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(blank=True, help_text="Technical type/class (e.g. 'Lathe')", max_length=100, null=True),
        ),
    ]
