# Generated by Django 5.2.9 on 2026-01-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0046_machine_category_alter_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending (Scheduled)'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('hold', 'On Hold'), ('canceled', 'Canceled'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
