# Generated by Codex on 2026-01-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0047_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialusage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.product'),
        ),
    ]
