# Generated by Codex on 2026-01-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0048_materialusage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='completion_requested',
            field=models.BooleanField(default=False, help_text='Worker requested completion'),
        ),
    ]
