# Generated by Django 5.2.9 on 2026-01-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0049_productionlog_completion_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='planner_action_required',
            field=models.BooleanField(default=False, help_text='Set true when final stage is approved and planner must close the WO.'),
        ),
    ]
