# Generated by Django 5.2.9 on 2026-01-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0050_workorder_planner_action_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='released_qty',
            field=models.PositiveIntegerField(default=0, help_text='Quantity released to the next stage from this work order.'),
        ),
    ]
