# Generated by Django 6.0.2 on 2026-02-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0053_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='category',
            field=models.CharField(blank=True, help_text='Stage category/type (e.g. Sewing)', max_length=100, null=True),
        ),
    ]
