# Generated by Codex on 2026-02-09
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('manufacturing', '0054_stage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='next_stage_ready',
            field=models.BooleanField(default=False, help_text='True when current stage is approved/QC complete and planner must start the next stage.'),
        ),
    ]
