# Generated by Codex on 2026-02-09
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('manufacturing', '0055_workorder_next_stage_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='Work order updated', max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='manufacturing.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

