# Generated by Django 6.0.2 on 2026-02-11 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0057_machine_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_supervisor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_worker_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='override_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='qc_auto_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='qc_sla_hours',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
