# Generated by Django 6.0.2 on 2026-02-11 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0059_workorder_step_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machinefault',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_supervisor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_worker_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='override_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='machinefault',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_auto_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_sla_hours',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='machinefault',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
