# Generated by Django 6.0.2 on 2026-02-17 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0060_machinefault_approved_at_machinefault_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycheck',
            name='scrap_compensated_at',
            field=models.DateTimeField(blank=True, help_text='When scrap compensation was last applied.', null=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='scrap_compensated_by',
            field=models.ForeignKey(blank=True, help_text='Last planner/admin who applied scrap compensation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_scrap_compensations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='scrap_compensated_qty',
            field=models.PositiveIntegerField(default=0, help_text='How many scrapped units were already added back to WO target by planner.'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='base_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Original planned quantity before scrap compensation increases.', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_scrap_compensation_task',
            field=models.BooleanField(default=False, help_text='True if this task was created as a scrap compensation replenishment.'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scrap_compensation_qty',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity added by planner to compensate scrap losses.'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scrap_source_quality_check',
            field=models.ForeignKey(blank=True, help_text='Quality check that triggered this scrap compensation task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_compensation_tasks', to='manufacturing.qualitycheck'),
        ),
    ]
